name: Test JMeter Action

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  JMeterTest:
    runs-on: ubuntu-latest
    steps:
      - name: JMeter Test
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: test_plan_login-service.jmx
          args: ""
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
