name: Test JMeter Action

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  JMeterTest:
    runs-on: ubuntu-latest
    steps:
    - name: Run JMeter Tests
      uses: rbhadti94/apache-jmeter-action@v0.5.0
      with:
        testFilePath: test_plan_login-service.jmx
        outputReportsFolder: reports/
